#!/bin/sh

# case $BLOCK_BUTTON in
# 	1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
# 	2) setsid -f "$TERMINAL" -e htop ;;
# 	3) notify-send "🖥 CPU module " "\- Shows CPU temperature.
# - Click to show intensive processes.
# - Middle click to open htop." ;;
# 	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
# esac

ctemp=$(sensors | awk '/Package id/ {$4 = substr($4, 2, length($4) - 5); print $4}')
# gtemp=$(sensors | awk '/edge/ {$2 = substr($2, 2, length($2) - 5); print $2}')

# printf "🌡️ C$ctemp° G$gtemp°"
printf "🌡️ $ctemp°"
