#!/bin/sh
#
vol="$(pamixer --get-volume)"

[ $(pamixer --get-mute) = true ] && printf "🔇%3d%s" $vol "%" && exit

if [ "$vol" -gt "49" ]; then
	icon="🔊"
elif [ "$vol" -eq "0" ]; then
	icon="🔇"
elif [ "$vol" -lt "25" ]; then
	icon="🔈"
else
	icon="🔉"
fi

printf "%s%3d%s" "$icon" "$vol" "%"
