#!/bin/sh

repos_dir="/var/www/git"

while true; do
	printf "new repository name: "
	read -r repo_name;
	repo_name=$(echo -n $repo_name | sed 's/ /-/g'):

	case $repo_name in
		*[\/\!\&\(\)\{\}\[\]@\#$%^*_+?]* ) \
		  echo 'name containing invalid character' ;;
		* ) break;
	esac
done

echo "creating new repository: \"$repo_name\""

mkdir -p "$repos_dir"/"$repo_name"/"$repo_name".git

ln -sf "$repos_dir"/"$repo_name"/"$repo_name".git /home/git

cp "$repos_dir"/dotfiles/dotfiles.git/hooks/post-receive
