#!/bin/bash

xinput --set-prop 13 'libinput Accel Profile Enabled' 0, 1

xinput --set-prop 14 'libinput Accel Profile Enabled' 0, 1

xinput --set-prop 'Logitech Wireless Mouse' 'libinput Accel Profile Enabled' 0, 1
