#!/bin/sh

col_gray1="#000000"
col_gray3="#cccccc"
col_darkmagenta="#8B008B"
col_gray4="#eeeeee"

dmenufont='Victor Mono:style=SemiBold:size=9';
# dmenufont="DejaVuSansMono Nerd Font:style=Regular:size=8"
# dmenuargs="-h 16 -b -l 10 -c"
dmenuargs="-i -h 16 -b -F $@"

dmenu_run_history -fn "$dmenufont" -nb $col_gray1 -nf $col_gray3 \
	-sb $col_darkmagenta -sf $col_gray4 $dmenuargs -p "Run:"
