#!/bin/bash

# swaps escape with caps-lock and lalt with lsuper

setxkbmap -option caps:swapescape

setxkbmap -option altwin:swap_lalt_lwin

setxkbmap -option altwin:swap_alt_win

# setxkbmap -option caps:super ; xcape -e 'Super_L=Escape'
