#!/bin/sh

# downloads a list of images given as input

[ -z "$1" ] && exit 1

while read line; do url="$line"; imgname=$(echo "$url" | cut -d "/" -f 12); \
	curl -# $url > $imgname; echo "\nDownloading: $imgname"; done < $1
