#!/bin/sh

# Prints a list of books in dmenu and opens the chosen one with pdfviewer
# The arguments receive are redirected to dmenu

# by github.com/klewer-martin

dir=$HOME/dox/books
pdfviewer=zathura
dmenucmds="-i -l 10 -h 14 -z 750 -bw 2 -c $@"

bookname=$(ls $dir | dmenu $dmenucmds)

[ -z "$bookname" ] && exit

[ $(file "$dir/$bookname" | cut -d ":" -f 2) = "directory" ] &&
	dir=$dir/$bookname && bookname=$(ls "$dir" | dmenu $dmenucmds)

[ -n "$bookname" ] && $pdfviewer "$dir/$bookname"
