#!/bin/sh

# Takes a screenshot of the screen and then saves it on the corresponding folder

FOLDER=~/pictures/screenshots
FILENAME=$FOLDER/$(date "+%H-%M-%S_%d-%m-%Y_scrot.png")

scrot $FILENAME

ACTION=$(dunstify -r 1 -t 5000 -h "string:bgcolor:#111111" "Saving screenshot ..." -h "string:bgcolor:#111111" "Click to open" --action=3,Open)

[ $ACTION -eq 3 ] && xdg-open $FILENAME;
