#!/bin/sh

# gets information about a public ip address
# usage: gip <PUBLIC IP>

if [ "$#" -eq 1 ]; then
	if expr "$@": '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; then
		for i in 1 2 3 4; do
			if [ $(echo "$@" | cut -d. -f$i) -gt 255 ]; then
			  echo "\"$@\" not an ip adress"
			  exit 1
			fi
		done
		curl --silent https://ipinfo.io/$@ | sed -e 's/"\|,\|  \|}//g' -e '1d' -e '/readme/d'
	else
		echo "usage: gip <PUBLIC IP>"
		exit 1
	fi
else
	echo "usage: gip <PUBLIC IP>"
	exit 1
fi
