#!/bin/bash

send_notification() {
	dunstify -r 199 -h "int:value:$1" "$2 Volume ($1%)" -t 2000;
	# dunstify "Signal $1 received"
}

case "$1" in
	1) pactl set-sink-mute @DEFAULT_SINK@ toggle; pkill -RTMIN+1 dwmblocks;;
    # 2) pactl set-sink-volume @DEFAULT_SINK@ +1; pkill -RTMIN+1 dwmblocks;;
    3) pavucontrol -t 3;;
	# 4) pactlsetvolume -i 1;;
	# 5) pactlsetvolume -d 1;;
	# 4) if [ "$curr" -lt "100" ]; then pactl set-sink-volume @DEFAULT_SINK@ +1%; pkill -RTMIN+1 dwmblocks fi;;
	# 5) pactl set-sink-volume @DEFAULT_SINK@ -1%; pkill -RTMIN+1 dwmblocks;;
	4) pamixer -i 1 & kill -35 $(pidof dwmblocks); exit;;
	5) pamixer -d 1 & kill -35 $(pidof dwmblocks); exit;;
esac
